import {
  faArrowLeft,
  faArrowTrendUp,
  faBars,
  faBoxArchive,
  faCalendarCheck,
  faCalendarDay,
  faChevronRight,
  faClockRotateLeft,
  faEye,
  faEyeSlash,
  faListCheck,
  faLeaf,
  faLock,
  faRotateRight,
  faTrash,
  faTriangleExclamation,
  faUsers,
  faUser,
  faXmark,
  faPen,
  faCircleCheck as fasCircleCheck,
  faCircleXmark as fasCircleXmark,
} from "@fortawesome/free-solid-svg-icons";
import {
  faCalendar,
  faCalendarDays,
  faCalendarXmark,
  faClock,
} from "@fortawesome/free-regular-svg-icons";

export const adminIcons = {
  username: faUser,
  password: faLock,
  passwordShow: faEye,
  passwordHide: faEyeSlash,
  appointmentsToday: faCalendarDay,
  pending: faClock,
  syncFailed: faTriangleExclamation,
  monthsManagement: faCalendarDays,
  dailyAppointments: faListCheck,
  syncRetries: faRotateRight,
  monthActive: faCalendarDay,
  monthInactive: faBoxArchive,
  monthFuture: faArrowTrendUp,
  monthPast: faClockRotateLeft,
  pastAppointments: faUsers,
  futureAppointments: faCalendarCheck,
  chevronRight: faChevronRight,
  menu: faBars,
  monthListCurrent: faCalendar,
  monthListPast: faCalendarXmark,
  monthListFuture: faClockRotateLeft,
  close: faXmark,
  back: faArrowLeft,
  monthDetailConfirmed: fasCircleCheck,
  monthDetailCancelled: fasCircleXmark,
  monthDetailAvailable: faCalendar,
  monthDetailBlocked: faLock,
  blockSchedule: faClock,
  blockConfirm: faLock,
  blockReasonRest: faLeaf,
  blockReasonPersonal: faUser,
  edit: faPen,
  delete: faTrash,
} as const;
