import {
  faArrowTrendUp,
  faBars,
  faBoxArchive,
  faCalendarCheck,
  faCalendarDay,
  faChevronRight,
  faClockRotateLeft,
  faEye,
  faEyeSlash,
  faListCheck,
  faLock,
  faRotateRight,
  faTriangleExclamation,
  faUsers,
  faUser,
  faCalendar
} from "@fortawesome/free-solid-svg-icons";
import {
  faCalendarDays,
  faCalendarXmark,
  faClock,
} from "@fortawesome/free-regular-svg-icons";

export const adminIcons = {
  username: faUser,
  password: faLock,
  passwordShow: faEye,
  passwordHide: faEyeSlash,
  appointmentsToday: faCalendarDay,
  pending: faClock,
  syncFailed: faTriangleExclamation,
  monthsManagement: faCalendarDays,
  dailyAppointments: faListCheck,
  syncRetries: faRotateRight,
  monthActive: faCalendarDay,
  monthInactive: faBoxArchive,
  monthFuture: faArrowTrendUp,
  monthPast: faClockRotateLeft,
  pastAppointments: faUsers,
  futureAppointments: faCalendarCheck,
  chevronRight: faChevronRight,
  menu: faBars,
  monthListCurrent: faCalendar,
  monthListPast: faCalendarXmark,
  monthListFuture: faClockRotateLeft,
} as const;
