import {
  faArrowLeft,
  faArrowRightFromBracket,
  faArrowTrendUp,
  faBars,
  faBoxArchive,
  faCircleUser as faUserCircle,
  faCalendarCheck,
  faCalendarDay,
  faChevronRight,
  faClockRotateLeft,
  faEye,
  faEyeSlash,
  faListCheck,
  faLeaf,
  faLock,
  faPhone,
  faGear,
  faRotateRight,
  faTrash,
  faTriangleExclamation,
  faUsers,
  faUser,
  faTableColumns,
  faXmark,
  faPen,
  faCircleXmark as fasCircleXmark,
  faCheckCircle as fasCheckCircle,
  faCalendarDays as fasCalendarDays,
  faBan,
  faCalendar as fasCalendar,
  faExternalLinkSquareAlt,
  faCircleArrowUp,
  faCircleArrowDown,
  faCircleMinus,
  faCircleInfo,
  faStar,
  faLightbulb,
  faPaperPlane,
} from "@fortawesome/free-solid-svg-icons";
import {
  faCalendar as farCalendar,
  faCalendarDays as farCalendarDays,
  faCalendarXmark,
  faClock,
} from "@fortawesome/free-regular-svg-icons";

export const adminIcons = {
  username: faUser,
  password: faLock,
  phone: faPhone,
  passwordShow: faEye,
  passwordHide: faEyeSlash,
  appointmentsToday: faCalendarDay,
  pending: faClock,
  syncFailed: faTriangleExclamation,
  dashboard: faTableColumns,
  monthsManagement: farCalendarDays,
  clients: faUsers,
  client: faUserCircle,
  clientsAnalytics: faUsers,
  dailyAppointments: faListCheck,
  syncRetries: faRotateRight,
  monthActive: faCalendarDay,
  monthInactive: faBoxArchive,
  monthFuture: faArrowTrendUp,
  monthPast: faClockRotateLeft,
  pastAppointments: faUsers,
  futureAppointments: faCalendarCheck,
  chevronRight: faChevronRight,
  menu: faBars,
  monthListCurrent: fasCalendar,
  monthListPast: faCalendarXmark,
  monthListFuture: faClockRotateLeft,
  close: faXmark,
  logout: faArrowRightFromBracket,
  back: faArrowLeft,
  monthDetailConfirmed: fasCheckCircle,
  monthDetailCancelled: fasCircleXmark,
  monthDetailAvailable: farCalendar,
  monthDetailBlocked: faLock,
  blockSchedule: faClock,
  blockConfirm: faLock,
  blockReasonRest: faLeaf,
  blockReasonPersonal: faUser,
  slotModeSettings: faGear,
  edit: faPen,
  delete: faTrash,
  addNewAppointment: fasCalendarDays,
  blockSpaces: faBan,
  shareAgenda: faExternalLinkSquareAlt,
  redirectLink: faExternalLinkSquareAlt,
  trendUp: faCircleArrowUp,
  trendDown: faCircleArrowDown,
  trendNeutral: faCircleMinus,
  info: faCircleInfo,
  busiestDay: faStar,
  dailyTip: faLightbulb,
  sendReminder: faPaperPlane,
} as const;
